### ISSUE TITLE
Gibts das Projekt noch?

### ISSUE THREAD

**Issue by xloterx** [NoSpread/eu_media#56]
Wahrscheinlich nicht der beste Ort um hier zu fragen, aber gibts das Projekt hier noch oder wurd das beendet, und wenn ja warum? Auf Insta & Twitter kommt ja nichts mehr und die Webseite scheint auch down zu sein.. Evtl. sieht das ja hier noch jemand.

**Comment by scientes** [comment]
Ja das Projekt gibt es noch. Die Website ist zz down weil die domainverlängerung verschlafen wurde glaub ich. Es läuft zz alles über den Discord. Die Petitionsseite z. B. hat dank YouTube ca 150k neue Unterschriften in den letzten Monaten bekommen.

**Comment by xloterx** [comment]
Ui, Leben.
